---
# defaults file for azure_infra
state: present
location: eastus
rg: "test"


admin_user: cloud-user
# This will be added to each instance's authorized_keys file
admin_pubkey: ''
# Path for the private key which will be added to localhost ssh_config for proxying through the bastion
admin_privkey: '~/.ssh/id_rsa'

# Dictionary of usernames (keys) and public SSH keys (values). These
# will be created on the bastion and added to the ocpadmin group. If
# this dictionary is not empty, the ocpadmin group will be configured
# for password-less sudo.
bastion_users: {}

# Service Principal name
sp_name: ''
# Place this in vars file that can be encrypted in root of play and not checked into SCM
sp_secret: ''


#######################
# RHSM
# Username / Password or
# Activation key / OrgId
#######################
rhsm_user: ''
rhsm_pass: ''
rhsm_key: ""
rhsm_org: ""
# Can specify separate pools so only Application nodes use paid subs
# or keep the same if only using one pool
rhsm_broker_pool: ""
rhsm_node_pool: ""
rhsm_repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-ose-3.10-rpms
  - rhel-7-fast-datapath-rpms
  - rhel-7-server-ansible-2.4-rpms
bastion_pkgs:
  - ansible
  - atomic-openshift-utils
  - atomic-openshift-clients
  - git
  - tmux
  - screen

#######################
# Custom Named Certs
#######################
# Router
#router_cert: '{"cafile": "/path/to/ca_cert", "certfile": "/path/to/fullchain.cer", "keyfile": "/vagrant/keys/domain.key"}'
# Master
#master_cert: '[{"cafile": "/path/to/ca_cert", "certfile": "/path/to/fullchain.cer", "keyfile": "/path/to/key/domain.key", "names": ["openshift.console.domain.name"]}]'

#######################
# Network
#######################
vnet_name: "{{ rg }}vnet"
vnet_cidr: "192.168.0.0/24"
master_subnet_cidr: "192.168.0.0/27"
infra_subnet_cidr:  "192.168.0.32/27"
cns_subnet_cidr:    "192.168.0.64/27"
app_subnet_cidr:    "192.168.0.128/25"

api_port: 443

vnet_preserve: false

#######################
# LB
#######################
# Name of Master LB
master_lb_public_ip: "masterExternalLB"

# Name of Router LB
router_lb_public_ip: "routerExternalLB"

#######################
# nodes
#######################
master_nodes: [1,2,3]
infra_nodes:  [1,2,3]
app_nodes:    [1,2,3]

# registry Storage Account Name
registry_storage_account: "{{ rg | regex_replace('-') }}"

#######################
# OCP Identity
# Use 'htpasswd -n <user>' to generate password hash. (htpasswd from httpd-tools RPM)
#######################
# Example with admin:redhat
openshift_master_htpasswd_users: {'admin': '$apr1$zAhyA9Ko$rBxBOwAwwtRuuaw8OtCwH0'}
openshift_master_identity_providers: [{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider' }]

#
#ocp_admin_passwd: 'redhat'

#######################
# deploy CNS
#######################
deploy_cns: true
deploy_cns_on_infra: true
deploy_metrics: true
deploy_logging: true
deploy_prometheus: true

# volume sizing defaults
metrics_volume_size: '20Gi'
logging_volume_size: '100Gi'
prometheus_volume_size: '20Gi'


#######################
#######################
# Don't change
#######################
#######################
bastion: "{{ rg }}b.{{ location }}.cloudapp.azure.com"
