---
- hosts: localhost
  roles:
    - { role: azure_cloud_provider }

- hosts: localhost
  roles:
    - { role: azure_add_new_nodes }

- hosts: localhost
  tasks:
    - name: Azure | template ansible hosts
      template:
        src: hosts_ocp_scale_pre.j2
        dest: hosts
        backup: yes

- hosts: localhost
  tasks:
    - name: Azure | refresh inventoy
      meta: refresh_inventory

# The Azure VMs are provisioned asynchronously. It can take some time
# until they are reachable via SSH, even after Azure reports that the
# provisioning state is "Succeeded".
- hosts: new_nodes
  gather_facts: no
  tasks:
    - name: Wait for nodes to become reachable via SSH
      wait_for_connection:
        sleep: 30
        timeout: 1200
        connect_timeout: 10

- hosts: new_nodes
  roles:
    - { role: ocp_pre }

- name: call openshift scaleup play for scaling infra/app nodes
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-node/scaleup.yml
  when:
    - new_infra_nodes or new_app_nodes

- name: call openshift scaleup master playbook for scaling master nodes
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-master/scaleup.yml
  when: new_master_nodes

- hosts: new_nodes
  roles:
    - { role: ocp_post }

- hosts: localhost
  tasks:
    - name: Azure | template ansible hosts
      template:
        src: hosts_ocp_scale_post.j2
        dest: hosts
        backup: yes

- hosts: localhost
  tasks:
    - name: Azure | refresh inventoy
      meta: refresh_inventory
