---
- name: Azure | Remove rh-cloud.repo
  file:
    path: /etc/yum.repos.d/rh-cloud.repo
    state: absent
  when: ('nodes' in group_names) or ('new_nodes' in group_names)

- name: Azure | Remove yum rhui load balancers
  file:
    path: /etc/yum.repos.d/rhui-load-balancers
    state: absent
  when: ('nodes' in group_names) or ('new_nodes' in group_names)

- name: Azure | Remove RHEL7 package
  yum:
    name: RHEL7
    state: absent
  when: ('nodes' in group_names) or ('new_nodes' in group_names)

- name: Azure | RHSM increase timeout
  lineinfile:
    dest: /etc/rhsm/rhsm.conf
    line: 'server_timeout=600'
    insertafter: '^proxy_password ='
  when: ('nodes' in group_names) or ('new_nodes' in group_names)

- name: Azure | RHSM unregister
  redhat_subscription:
    state: absent
  register: task_result
  until: task_result is success
  retries: 10
  delay: 30
  when: ('nodes' in group_names) or ('new_nodes' in group_names)

- name: Azure | RHSM register (username-passwd) Master-Infra-CNS
  redhat_subscription:
    state: present
    username: "{{ rhsm_user }}"
    password: "{{ rhsm_pass }}"
    pool_ids: "{{ rhsm_broker_pool }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 30
  when:
    - ( inventory_hostname in groups.masters ) or
      ( inventory_hostname in groups.infra ) or
      ( inventory_hostname in groups.glusterfs )
    - rhsm_user is defined and rhsm_user != ""
    - rhsm_pass is defined and rhsm_pass != ""

- name: Azure | RHSM register (activation-key) Master-Infra-CNS
  redhat_subscription:
    state: present
    activationkey: "{{ rhsm_key }}"
    org_id: "{{ rhsm_org }}"
    pool_ids: "{{ rhsm_broker_pool }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 30
  when:
    - ( inventory_hostname in groups.masters ) or
      ( inventory_hostname in groups.infra )   or
      ( inventory_hostname in groups.glusterfs )
    - rhsm_key is defined and rhsm_key != ""
    - rhsm_org is defined and rhsm_org != ""

- name: remove premium pool id | Master and Infra subscription only
  redhat_subscription:
    state: absent
    pool_ids: "{{ rhsm_node_pool }}"
  when:
    - ( inventory_hostname in groups.masters ) or
      ( inventory_hostname in groups.infra )   or
      ( inventory_hostname in groups.glusterfs )
    - rhsm_node_pool != rhsm_broker_pool

- name: Azure | RHSM register (username-passwd) Application nodes
  redhat_subscription:
    state: present
    username: "{{ rhsm_user }}"
    password: "{{ rhsm_pass }}"
    pool_ids: "{{ rhsm_node_pool }}"
  register: task_result
  serial: 5
  until: task_result is success
  retries: 10
  delay: 30
  when:
    - inventory_hostname not in groups.masters
    - inventory_hostname not in groups.infra
    - inventory_hostname not in groups.glusterfs
    - rhsm_user is defined and rhsm_user != ""
    - rhsm_pass is defined and rhsm_pass != ""

- name: Azure | RHSM register (activation-key) Application nodes
  redhat_subscription:
    state: present
    activationkey: "{{ rhsm_key }}"
    org_id: "{{ rhsm_org }}"
    pool_ids: "{{ rhsm_node_pool }}"
  register: task_result
  serial: 5
  until: task_result is success
  retries: 10
  delay: 30
  when:
    - inventory_hostname not in groups.masters
    - inventory_hostname not in groups.infra
    - inventory_hostname not in groups.glusterfs
    - rhsm_key is defined and rhsm_key != ""
    - rhsm_org is defined and rhsm_org != ""

- name: Azure | RHSM disable all repos
  rhsm_repository:
    name: '*'
    state: disabled
  register: repo_result
  until: repo_result is success
  retries: 10
  delay: 30
  when: ('nodes' in group_names) or ('new_nodes' in group_names)

- name: Azure | RHSM enable repos for OCP
  rhsm_repository:
    name: "{{ rhsm_repos }}"
    state: enabled
  until: repo_result is success
  serial: 5
  retries: 10
  delay: 30
  register: repo_result
  when: ('nodes' in group_names) or ('new_nodes' in group_names)

- name: Azure | Install OCP client
  yum:
    name: atomic-openshift-clients
    state: latest
  when: "'masters' in group_names"
